### ISSUE TITLE
Jewels: drawings vs. architectural drawings

### ISSUE THREAD

**Issue by melanieWacker** [melanieWacker/dlc-metadata-cleanup#13]
Wondering if maybe some of the drawings should be architectural drawings? 
"Graphic delineations made for the design and construction (or documentation of design and construction) of sites, structures, details, fixtures, furnishings, and decorations, as well as other objects designed by an architect or architectural office."

**Comment by ErinPetrella** [comment]
Drawings that fell within the above definition were re-assigned as architectural drawings.
