### ISSUE TITLE
Jewels: Subject Social Service

### ISSUE THREAD

**Issue by melanieWacker** [melanieWacker/dlc-metadata-cleanup#14]
The broad categories coming from the original site were changed to lcsh -- which works alright for "Music" for example. However, the items labeled "Social service" came from a category that was originally called "Philanthropy, Social Services, Human Rights". So by converting that to "social services" we ended up with a book about torture and political prosecution in that category. I've fixed that one, but I think the other items with that subject may need review as well.

**Comment by ErinPetrella** [comment]
The "Social Services" category was reviewed, and records to which the subject does not apply were reassigned to other categories.
