### ISSUE TITLE
Jewels: Subjects vs. Genre

### ISSUE THREAD

**Issue by melanieWacker** [melanieWacker/dlc-metadata-cleanup#20]
Please take another look at the subjects. I think a few genres have crept into the subjects. E.g. the resource is a dissertation, but not about a dissertation.

**Comment by ErinPetrella** [comment]
To clarify for future remediation: do we ever use genre as a top-level element, or subject_genre? I can't find examples of either usage in other data sets, and since this is added data, not converted data, and is therefore not in the conversion table, I just want to clarify.

**Comment by melanieWacker** [comment]
We would use the top level element <genre>. subject/genre would only occur as part of a subject string. So if there is something that you feel strongly about encoding, feel free to add a column for genre, genre_authority and the authority URI. Just make sure to also update the style sheet and the Jewels data dictionary accordingly: https://wiki.cul.columbia.edu/pages/viewpage.action?pageId=24904851

**Comment by ErinPetrella** [comment]
The style sheet has been updated. Two more issues:
1. Should we use LCSH or FAST?
2. I'd like to quickly check Dramatic Museum and Judging a Book re: this issue, and update them accordingly. This shouldn't be an issue since we've not yet converted them to MODS, but I'll need to update the data files here on GitHub.

**Comment by melanieWacker** [comment]
Let's give FAST priority to be consistent -- which means to update our FAST guidelines here: https://wiki.cul.columbia.edu/display/metadata/Adding+FAST+Subject+Headings+for+Digital+Projects
If there is nothing in fast for a needed genre you can also use the new Genre/Form terms searchable through ClassificationWeb.

**Comment by ErinPetrella** [comment]
Subjects and genres updated per discussion above, as well as wiki documentation.
