### ISSUE TITLE
Jewels: Beggar's Opera

### ISSUE THREAD

**Issue by melanieWacker** [melanieWacker/dlc-metadata-cleanup#23]
items 224 and 224_000 link to the wrong subject title. The words and music depicted on the playing cards are actually those of the Beggar's Opera written by John Gay, not John Christopher Pepusch

**Comment by melanieWacker** [comment]
Also, please use FAST for titles:
http://id.worldcat.org/fast/1357473
FAST guidelines: https://wiki.cul.columbia.edu/display/metadata/Adding+FAST+Subject+Headings+for+Digital+Projects

**Comment by ErinPetrella** [comment]
Updated subject_titles to Fast headings, and reassigned #224.
