### ISSUE TITLE
Jewels: Collection names

### ISSUE THREAD

**Issue by melanieWacker** [melanieWacker/dlc-metadata-cleanup#27]
Collection names: We used to transcribe the form as found in the archival collection portal exactly, including capitalization. We have moved to using the form as found in the archival collection portal with title case UNLESS there are already a lot of items (other than those in the Jewels project) that use the lower case form in the SCV and DCV. Those will get cleaned up at a later point. For the time being we are trying to avoid split files which can be caused by different capitalization. Please also consult the CUL_Collection_Names on Google drive and let me know if there are any discrepancies.
Could you change collection names to title case (where appropriate)?

**Comment by ErinPetrella** [comment]
Collection Names  in Jewels updated to title case, except:

1. Greene & Greene architectural drawings, papers and photographs (257 records in SCV)
2. Herbert H. Lehman papers (32,000 records in SCV)

Note: 
Tennessee Williams papers has 12 records in SCV
Varian Fry papers has 8 records in SCV
