### ISSUE TITLE
Jewels: Chinese Paper Gods

### ISSUE THREAD

**Issue by melanieWacker** [melanieWacker/dlc-metadata-cleanup#29]
This is related to 033 and 033_000: This is actually a compilation of two different images. Both are included in the "Chinese Paper Gods" digital project. I think I located the correct "gods" so that we can use that information (e.g. that they are from the Anne S. Goodrich Collection plus the names of the gods) -- but please take a look and double-check me on that.
https://dlc.library.columbia.edu/catalog/ldpd:115059
https://dlc.library.columbia.edu/catalog/ldpd:114770
https://dlc.library.columbia.edu/catalog/ldpd:115097

**Comment by ErinPetrella** [comment]
Yes, these seem right, and they are listed in the description on their exhibition page in Jewels. Added collection name and names of gods.
